GET http://localhost:3012/subscribers

###
GET http://localhost:3012/subscribers/stephane

###
POST http://localhost:3012/subscribers/
Content-Type: application/json

{
"name": "stephane",
"subscribedToChannel": "customChannel"
}

###
DELETE http://localhost:3012/subscribers/stephane

###
PATCH http://localhost:3012/subscribers/stephane
Content-Type: application/json

{
"name": "stephaneNewName3",
"subscribedToChannel": "customChannel"
}